# Generated by Django 5.0.7 on 2024-07-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='edad',
            field=models.CharField(default=1, max_length=50, verbose_name='edad'),
            preserve_default=False,
        ),
    ]
