# Generated by Django 5.0.7 on 2024-07-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista', '0002_pagina_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destrezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destreza', models.CharField(max_length=50, verbose_name='destreza')),
            ],
            options={
                'verbose_name': 'Destreza',
                'verbose_name_plural': 'Destrezas',
            },
        ),
    ]
