# Generated by Django 5.0.7 on 2024-07-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista', '0003_destrezas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='destrezas',
            field=models.ManyToManyField(to='vista.destrezas'),
        ),
    ]
