# Generated by Django 5.0.7 on 2024-07-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista', '0004_pagina_destrezas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='nombresC',
            field=models.CharField(default=1, max_length=50, verbose_name='nombresC'),
            preserve_default=False,
        ),
    ]
